package com.triagemate.triage.control.decision;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.triagemate.contracts.events.EventEnvelope;
import com.triagemate.contracts.events.v1.InputReceivedV1;
import org.slf4j.MDC;
import org.springframework.stereotype.Component;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

@Component
public class DecisionContextFactory {

    private final ObjectMapper objectMapper;

    public DecisionContextFactory(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    private static String firstNonNull(String first, String second) {
        return first != null ? first : second;
    }

    /**
     * Builds a {@link DecisionContext} from the given envelope.
     *
     * <p>Trace identifiers are read from the envelope's trace header first;
     * MDC values (which may contain fallback IDs generated by the consumer)
     * are used only when the envelope trace is absent or incomplete.
     */
    public DecisionContext<InputReceivedV1> fromEnvelope(EventEnvelope<?> envelope) {
        EventEnvelope.Trace envelopeTrace = envelope.trace();

        Map<String, String> trace = new HashMap<>();
        trace.put("requestId", firstNonNull(
                envelopeTrace != null ? envelopeTrace.requestId() : null,
                MDC.get("requestId")));
        trace.put("correlationId", firstNonNull(
                envelopeTrace != null ? envelopeTrace.correlationId() : null,
                MDC.get("correlationId")));

        InputReceivedV1 payload = objectMapper.convertValue(envelope.payload(), InputReceivedV1.class);

        return DecisionContext.of(
                envelope.eventId(),
                envelope.eventType(),
                envelope.eventVersion(),
                envelope.occurredAt(),
                Collections.unmodifiableMap(trace),
                payload
        );
    }
}
