spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/triagemate
    username: triagemate
    password: triagemate

  kafka:
    bootstrap-servers: kafka:9092

triagemate:
  kafka:
    topics:
      input-received-v1: triagemate.ingest.input-received.v1

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
